unit MyOTAWizard.ProjectMenu.Consts;

interface

uses
  ToolsAPI;

const
  MY_MENU_SEPARATOR = '-';
  MY_MENU_CAPTION  = 'AAB Softwares';
  MY_MENU_POSITION = pmmpRunNoDebug + 200;

  MY_MENU_ITEM_ADICIONAR_PROJETO_CAPTION  = 'Adicionar projeto à lista';
  MY_MENU_ITEM_ADICIONAR_PROJETO_POSITION = MY_MENU_POSITION + 10;

  MY_MENU_ITEM_BOSS_INIT_CAPTION  = 'Boss init';
  MY_MENU_ITEM_BOSS_INIT_POSITION = MY_MENU_POSITION + 20;

  MY_MENU_ITEM_BOSS_INSTALL_CAPTION  = 'Boss install';
  MY_MENU_ITEM_BOSS_INSTALL_POSITION = MY_MENU_POSITION + 22;

  MY_MENU_ITEM_BOSS_UPDATE_CAPTION  = 'Boss update';
  MY_MENU_ITEM_BOSS_UPDATE_POSITION = MY_MENU_POSITION + 24;

implementation

end.
